### ISSUE TITLE
Recording has started to not work

### ISSUE THREAD

**Issue by Eddye101** [iabarca/lawena-recording-tool#113]
Recording just causes the game to speed up and slow down at random speeds. I have tried rebinding P and  using the record command (startrecording). If I do stoprecording after this is says 'no movie started' and no frames appear in my frames folder.  This has only recently come up after I've been using lawena for a while. I have also tried re-downloading it.

**Comment by quanticc** [comment]
This is currently a known issue caused by the Jungle Inferno update where the movie folder must be under your tf dir for it work. See the thread after https://github.com/quanticc/lawena-recording-tool/issues/82#issuecomment-345544117 to get more context.

Can you check your movie folder is under tf folder?

**Comment by Eddye101** [comment]
It's working again, thanks :)
