### ISSUE TITLE
Can't change movie folder

### ISSUE THREAD

**Issue by Cod-SA** [iabarca/lawena-recording-tool#51]
I change my movie folder and save, but when I go back to File/Change Movie Folder, it's back to default (Documents).

**Comment by iabarca** [comment]
Hi, this is an issue only with the user interface, since the folder displayed on that dialog is not the same as the movie folder.

I'll fix this to give you more feedback but your movie folder should already be changed. Try recording some frames or opening the ``settings.lwf`` (v4.1) or ``profiles.json`` (v4.2) with notepad to confirm it is in fact changed.

**Comment by Cod-SA** [comment]
Thanks very much. settings.lwf confirmed it has changed.
