### ISSUE TITLE
No movie started.

### ISSUE THREAD

**Issue by Mixonpro** [iabarca/lawena-recording-tool#57]
Need a help. I recording TF2 demos with lawena, press P. Game begin lags. Then I again press P to stop recording, but nothing has not recorded. I checked movie folder - empty. Also, after stopping recording I saw "No movie started." in console.

**Comment by iabarca** [comment]
It's possible that the recording folder can't be accessed by Source Recorder, can you try using a simple folder name, like ``C:\Frames``?

The no movie started message appears as a result of the ``endmovie`` command. But after that you should get something like "Started recording movie, frames will record after console is cleared..." along with the slowdown due to ``host_framerate 0.001``. If you get the slowdown but no frames nor console message it's certainly related to the ``startmovie`` command.

**Comment by Februari** [comment]
I got the exact same problem today after getting the latest release, the thing is tho, earlier today, still after updating i recorded 2 clips, without any problem whatsoever. Only idea i had was that the clip was as solly, and i have a solly config, altho it shouldnt be loaded with lawena. On the other side, the other clips from earlier today were also soldier clips, so that cant be the problem. Have not yet tested with other clips, but manual recordings nor using "exec recbindings" work.

**Comment by iabarca** [comment]
Is it possible that some demo you played changed your P key bind? Rebind by typing ``bind P startrecording`` in console.

If you are in a hurry record manually using the following series of commands:

```
host_framerate 240
host_timescale 0.001
startmovie "C:\sequence1_" tga wav
```

Customize the folder in ``startmovie`` and the FPS in ``host_framerate`` to your liking. Remember to add the filename your recorded frames will share.

**Comment by Februari** [comment]
When writing startrecording in console i get the message "No more movie slots." What can this mean?

**Comment by Februari** [comment]
Fixed the problem, i had old o and p frames in my folder preventing new frame creation. Thank you for the quick support though! The person above might have the same problem, not sure, but it might be a good idea to add this in the frequent problem list, as i did not know about this until i searched the problem.

**Comment by iabarca** [comment]
Thanks to you for using the issues page as intended and searching beforehand. Also that's a great suggestion too, maybe I can add a list of common issues to the wiki.

I think @Mixonpro had a different problem than yours though. It seemed to me that the game was actually recording frames but they weren't saved to disk. I've seen that happening when the path is invalid or has special characters. It's an issue on TF2 or Source Recorder side.
