### ISSUE TITLE
Various issues since last updates.

### ISSUE THREAD

**Issue by Kaneco** [iabarca/lawena-recording-tool#61]
Hey there. Ive been having numerous issues since the last update.

First the pixel fog option still seems bugged. I have to click Enable Pixel Fog to disable it.

Second all the "no announcer voices" and "no dominations" .vpks seem broken since the last update that valve changed the audio format to .mp3

Also been having issues with snd_mute_losefocus, where I hear sound while tabbed out while It didn't happen before. But this one might be just on my end.

**Comment by iabarca** [comment]
Apparently ``r_pixelfog 0`` enables the fog instead of disabling it, like every other zero value command. wtf.. Will fix in a while.

Also I'll start getting the list of files to build the vpks using mp3.

For your third issue, I'd have to ask you to run a little test for me if possible, to see if it's related to a recent change I made. Can you edit your ``recbindings.cfg`` file, find this line (line 63 on default file):

``alias startrecording "host_timescale 0.001; snd_soundmixer Default_Mix; recframerate; bind P stoprecording; namescroll"``

and change it to:

``alias startrecording "host_timescale 0.001; recframerate; bind P stoprecording; namescroll"``

And let me know if that solves it.

**Comment by iabarca** [comment]
Pushed a partial update to preview branch, with the new vpks and the pixelfog thing. Will be testing them now.

**Comment by Kaneco** [comment]
Sorry about not giving feedback after this, but every issue seems to have been solved, also I think removing pixelfog was the best decision. Good work!
