### ISSUE TITLE
Java error when trying to delete movie segments.

### ISSUE THREAD

**Issue by Kaneco** [iabarca/lawena-recording-tool#64]
When I try to click delete movie segments in the recordings folder but there aren't actually any movie segments recorded with lawena, but there are still other kinds of files or tgas there I get the following error
![1](https://cloud.githubusercontent.com/assets/8399240/9373387/aca65930-46e1-11e5-8573-78092b2bcb1f.png)

This happens because I export my SFM recordings to the same folder as lawena recordings and when I try to click that button after recording with sfm I always get that error.

**Comment by iabarca** [comment]
This is a bug caused by the file mixup you mention. The program looks for ``*.wav`` files with the format: ``a1_.wav`` to extract the segment name (before the underscore) to show you a dialog asking for which segments to delete. If there are WAV files but no underscore on the name this error happens.

Pushing a patch soon. The behavior should only delete Lawena segments and never delete files with a broad wildcard, it should not be a "Delete all files in the recording folder" button. If there are no files that match the above naming convention, it will output "There are no segments to delete" to avoid deleting the wrong files.
