### ISSUE TITLE
Playdemo Crash

### ISSUE THREAD

**Issue by code-al** [iabarca/lawena-recording-tool#76]
Whenever I play a demo it's runs normally for a few seconds then crashes to the desktop. I've tried it with multiple demos all of them ran fine in my tf2 but crashes whenever I use lawena. I have no idea what's causing it.

**Comment by iabarca** [comment]
If you haven't tried anything special my first guess would be the multicore rendering setting. Have you tried using ``mat_queue_mode 1`` before launching the demo? Lawena uses 0 by default in its graphic config which causes instability in some systems.

For some people this is enough, like for instance in this issue: #52 

If this does not help, then I would suggest trying to isolate the problem so you can at least record your frames, for instance:
(1) run the game not using the ``recording.cfg`` config file (rename it before launch)
(2) using a lower quality (``-dxlevel``) setting.
(3) adding ``-default`` to the custom launch settings (Advanced menu). This will surely make it work since it blocks all of Lawena settings while preserving video capturing capabilities.

If (1) works and you wish to get more quality, you can try configuring the game from the inside after being run with Lawena.

**Comment by code-al** [comment]
Tried everything, none of them worked. I noticed something though, my game crashes whenever an explosion happens. For instance, the demo would run fine but it crashes whenever I rocketjump or hit someone with explosives. I tried disabling everything including mods but still crashes. I confirmed that it's playing normally in my tf2 client.

**Comment by iabarca** [comment]
I'd thought about Lawena missing a file somehow but I'll have to investigate more tomorrow to confirm.

Also I was wondering since you can make it work, do you normally use a special performance config? Because it seems related to the load on your system.

I would recommend running Lawena using ``-default`` as is almost equivalent to running with default TF2. The only differences are the launch parameters.

Since that isn't working, does default TF2 (not using lawena) makes it crash? To test this add ``-default`` to launch parameters from Steam library.

If that test works for you (default TF2 without Lawena does not causes crashes) then I'm running out of options to test. It would mean that there's some bind or launch parameter or maybe a file? added from Lawena causing problems, but I can't conclude that for the moment.

If the test doesn't work (still crashes), then it's related to your graphic config/load and the demo. You would have to match the graphic settings from your game to run with Lawena (using your config inside Lawena) or construct manually in your normal TF2 an environment where you can record. There's also the option to try another recording tool that can help us find differences. I'm not familiar with the current state of those though.

I will be posting here whenever I find more info. I might need to ask for a demo of yours to replicate the scenario in my computer later.

**Comment by code-al** [comment]
I tried adding `-default` parameter and it crashed my tf2 client. 
here's my [config](http://pastebin.com/dyid1AkG)
here's my [main](http://pastebin.com/NDVqu0yi) (autoexec)

I don't really use any graphics configs, as far as i can remember, the only change i've done before lawena began crashing was adding `sv_forcepreload` I believe. It's kinda weird because It was working ok a few minutes before.

**Comment by code-al** [comment]
Here's the demo https://www.dropbox.com/s/gfkuc2gbeq7mjz0/20160124_1329_cp_snakewater_final1_red_blu.rar?dl=0

**Comment by nobelharvards** [comment]
Hi, I'm the idiot who tried having "exec autoexec" in every class script and being unable to get any clips out of demos while I had that.

I am thinking this person possibly had weapon explosion scripts.
http://www.teamfortress.tv/25647

Perhaps that script is also "saved" in the demo file in a similar behaviour to "exec autoexec" in class configs?

I have no technical expertise, take all this with a grain of salt.

**Comment by code-al** [comment]
Yes in fact I do have the no explosion script. I think I did try and include that while playing my demo but didn't work. Might test it again.

**Comment by iabarca** [comment]
I've included something in v4.1.11 that attempts to fix these kind of crashes.
