### ISSUE TITLE
Break the default TF2 Hud

### ISSUE THREAD

**Issue by MiddayFury** [iabarca/lawena-recording-tool#81]
I installed this program so that I could use it as intended. I went to go try it out, and it seems to work okay, despite it not recording. 

Anyway, when I launched TF2 without Lawena, I noticed it broke several features about the default hud. Such as; My chat wouldn't show up unless I pressed the text key and my taunt menu wasn't showing up and it STILL isn't. 

I had to delete the hud files and reinstall them. And I am still having problems.  I finally was able to fix my chat, but my taunt menu is still broken thanks to this program. I will never use it again.

**Comment by iabarca** [comment]
First of all, sorry about the problems you had while attempting to use the software. Lawena can't modify the default HUD, in fact there are no default HUD files you can delete, they are present in the valve packed VPK files. What the program does is using a custom HUD and a custom "cfg" folder that is removed once the program exits, restoring your previous "cfg" and "custom" folders. It uses folders named "lwrtcfg" and "lwrtcustom" for this process.

If this removal is not done by the program automatically, you will get an error message and will possibly have to manually restore the files, otherwise you could launch the game with remaining Lawena files in your cfg and custom folders such as its configs (You would see "Lawena Recording Tool" in the console and/or have its binds) and its HUDs.

A backup of your files is always made before moving around the folders, and it is placed in your TF folder. You can restore from those.

As for the taunt action, remember that the original bind for that is ``bind "g" "+taunt"``. TF2 just picks up whatever you have as config.cfg in the game.
