### ISSUE TITLE
crashes as soon as a start lawena, deletes custom and cfg folder contents

### ISSUE THREAD

**Issue by blungo** [iabarca/lawena-recording-tool#89]
it looks like it attmepts to start then just fails to launch and says that it "didnt replace my files", it also deletes the contents of my custom and cfg folder (hud and class cfgs)

ive tried new and old versions of lawena with no success

**Comment by quanticc** [comment]
Please attach your Lawena log file here (as a .txt) or paste it into http://hastebin.com/

File is located in the `lawena` folder and it's called `lawena.0.0.log`

About the deletion of files, there are zipped backups in your TF folder each time you launch it.

**Comment by blungo** [comment]
the zip files are empty

http://pastebin.com/HdnheJEP

**Comment by quanticc** [comment]
Run a brand new install (4.1) and avoid running Lawena while TF2 is in the background, use the program to launch the game.

The "[Access denied exception](https://github.com/quanticc/lawena-recording-tool/wiki/FAQ#lawena-is-not-replacing-my-cfg-andor-hud-files-correctly-and-im-getting-an-accessdeniedexception-in-the-log-whats-wrong)" is caused by resources that are not released properly by Steam and it might cause conflicts. Lawena tries to solve those but it inconsistently fails. Try running the tool before having run TF2 after you boot the computer to isolate the issue.

Always have a side backup of your custom folder. Sorry for the inconveniences.

**Comment by blungo** [comment]
the new install doesnt change a thing

im really confused why the happens, i swear it was working a month ago, the same problem happened and then i resolved it somehow. did a tf2 update break it?

**Comment by quanticc** [comment]
I can't reproduce therefore can't fix at the moment. I tried messing with the read-only flag of some key folders and couldn't make it happen. I know it's a permission or locking issue that's causing Lawena to be unable to delete a folder.

If that doesn't help then try running the tool without having run TF2 before, restarting PC if needed. Before you do, check you don't have folders named lwrtcfg or lwrtcustom in your tf folder. If you do, manually revert your files to the correct folders and delete the ones starting with lwrt.
