### ISSUE TITLE
cant enable netgraph 

### ISSUE THREAD

**Issue by blungo** [iabarca/lawena-recording-tool#91]
i tried to make a new cfg and everything but i come back to the settings.cfg and net_graph is set to 0

**Comment by quanticc** [comment]
net_graph is being disabled because it normally disrupts the movie recording process.

I will reorder the commands auto-generated in settings.cfg so you can use the Custom Settings dialog, accessed through Advanced menu.

![Custom Settings dialog, accessed through Advanced menu](https://cloud.githubusercontent.com/assets/1908830/19843986/9d5a1ae2-9f06-11e6-8795-2102719c4653.png)

This will be available in the preview branch. Select it by using **Help - About** menu, then go to **Select updater branch**, select "preview-v4.1" then press OK and restart application.
