### ISSUE TITLE
says: failed to save lawena settings to file

### ISSUE THREAD

**Issue by StepanDachovsky** [iabarca/lawena-recording-tool#92]
i will normally download, then run the lawena i will get to jar file lawena, open it and start it then i will click on start team fortress 2 and? failed to save lawena settings to file, if you don´t know what do i think i have recorded some video prewiew : https://www.youtube.com/watch?v=-z3n0tw13B8&feature=youtu.be 
if its some very stoopid reason sorry but i am in the world of files and documents very bad.

**Comment by quanticc** [comment]
Please execute Lawena from the lawena.exe file in the extracted zip (0:34 in your video) instead of going into the lawena folder. Running it like your video might cause permission problems and break the game launching process.

![2016-11-28_16-33-55](https://cloud.githubusercontent.com/assets/1908830/20682893/a61caa44-b588-11e6-9e80-fc6110ddf29d.png)

If that doesn't fix it, then I think Lawena autodetected your TF2 folder incorrectly. Can you try selecting it manually? Go to File menu then "Change TF2 folder"

![javaw_2016-11-28_16-33-02](https://cloud.githubusercontent.com/assets/1908830/20682871/8bffa18e-b588-11e6-8aff-79e78f505f3d.png)

Let me know what worked. The log file should solve the issue in case none of these work.

**Comment by StepanDachovsky** [comment]
Um sorry for no answers i was for 4 days out now i have tried it but at the same spot as failed lawena settings to file is now: Failed to replace custom files

**Comment by StepanDachovsky** [comment]
Sorry for this comment i am so stupid :D i had tf already launched so i couldn´t open that from lawena i think that everything is good now if i will have some problems i will write something
