### ISSUE TITLE
Fatal crash (after the creators update)

### ISSUE THREAD

**Issue by adamgemmell** [iabarca/lawena-recording-tool#96]
Error on launch: https://pastebin.com/7NeyCkzJ
Log file: https://pastebin.com/vbLq8XnG (some info redacted)

Seemed to occur after the W10 update, was working about a week ago :(

**Comment by quanticc** [comment]
I am not able to replicate this issue yet, tried with multiple JDKs and launching via .EXE and via command-line.

**Comment by adamgemmell** [comment]
i tried with multiple jdks and both exe/command line, still got crashes. i just noticed lawena.0.0.log, which abruptly stops:


``[19-04-2017 21:32:55] Checking for game path at c:\program files (x86)\steam\SteamApps\common\Team Fortress 2\tf
[19-04-2017 21:32:55] Checking for movie path at``

**Comment by quanticc** [comment]
Yeah the crash happens when it's ready to display main window. It's a Swing (GUI Toolkit) related crash. For instance the following lines are missing from your logs:

```
[18:56:45] *** Restore and cleanup completed
[18:56:45] Init complete - Ready to display GUI
[18:56:45] Preparing to display main user interface
[18:56:45] Lawena Recording Tool 4.1.14-1-g05a52cd build 20160804125646
```

**Comment by quanticc** [comment]
I've added something to the preview branch that I would like you to test. Normally you could do these by switching to preview branch but since you can't launch the program, follow these steps instead:

1. Download this version: [lawena-preview-4.1.16-2-g0a93ac8.zip](https://github.com/quanticc/lawena-recording-tool/files/939017/lawena-preview-4.1.16-2-g0a93ac8.zip)
2. Don't run yet and instead go to "lawena" folder and create a file called `settings.lwf`. Make sure it's not ending in .txt
![settings.lwf](http://i.imgur.com/PyoyjFv.png)
3. Open in text editor and add this line to it.
```
SetSystemLookAndFeel=false
```
4. Save and Launch Lawena

It will not try to use "native" Windows look, it's worth a try I guess.

**Comment by adamgemmell** [comment]
Nice, it launches fine now (with the ugly swing looks). still crashes if i delete settings.lwf

**Comment by adamgemmell** [comment]
(mb, didn't mean to close it)

**Comment by quanticc** [comment]
Thanks for letting me know, it seems to be a Java/Swing issue then.

Just to have more info about trying to reproduce the problem, is your display high DPI or something out of the ordinary?

**Comment by adamgemmell** [comment]
it's 144Hz, but other than that it's just 1080p. havent done any ricing or other modifications to the window manager either if that matters. i can ask some others if they have issues. interestingly intellij launches fine, which i believe is a swing application. i'll use the workaround for now and hope some update somewhere fixes it, cheers for the help
